SELECT COLUMN_NAME, TABLE_NAME, DATA_TYPE, IS_NULLABLE, TABLE_CATALOG
FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME IN (
   SELECT COLUMN_NAME
   FROM INFORMATION_SCHEMA.COLUMNS
   WHERE TABLE_NAME IN
		(SELECT ClassTableName FROM cms_class
		WHERE ClassIsDocumentType = 1)
   GROUP BY COLUMN_NAME
   HAVING COUNT(DISTINCT DATA_TYPE) > 1
)
ORDER BY COLUMN_NAME
